openapi: 3.0.0
info:
  title: Simple Example
  version: 1.0.0
paths:
  /customers:
    get:
      summary: List all customers
      operationId: listCustomers
      tags:
        - customers
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of customers
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Customer:
      required:
        - id
        - name
        - points
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        points:
          type: integer
          format: int64
        tag:
          type: string
    Customers:
      type: array
      items:
        $ref: "#/components/schemas/Customer"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
